- name: Listen for newly added ConfigMap resources
  hosts: all
  sources:
    - ansible.eda.k8s:
        api_version: v1
        kind: ConfigMap
        namespace: ansible-automation-platform
  rules:
    - name: Notify
    condition: event.type == "ADDED"
    action:
      run_job_template:
        name: test_jt
        organization: Default
        job_args:
          extra_vars:
            dev_var: 9
          inventory: 2
          instance_groups:
          - 3
          credentials:
          - 4
