- name: Listen for newly added ConfigMap resources
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ConfigMap
        namespace: ansible-automation-platform
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
        run_playbook:
          name: vars_check.yaml
          extra_vars:
            cluster_name: "abc"
